# Generated by Django 4.2.6 on 2023-11-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juneapp', '0003_june'),
    ]

    operations = [
        migrations.AddField(
            model_name='june',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
