# Generated by Django 4.2.6 on 2023-11-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juneapp', '0004_june_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='june',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
