# Generated by Django 4.2.6 on 2023-11-09 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juneapp', '0005_remove_june_profile_image_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='june',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='june_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
