# Generated by Django 4.2.6 on 2023-11-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juneapp', '0007_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homepage_link',
            new_name='website_link',
        ),
    ]
